### PR TITLE
SC-17013 Add UJS troubleshooting page

### PR DESCRIPTION
**Pull request by HSSalman**
This PR adds a UJS troubleshooting page, which covers some of the things we do when writing our own scripts or troubleshooting those sent to us by users. @hasan-wajahat if you have any suggestions on what to add/change feel free to mention them and I'll expand what's here. Also added @fulyauluturk as a reviewer to see if everything makes sense from the perspective of someone who doesn't deal with these scripts often.

### CODE REVIEW

**Comment by otisg** [comment]
👍 
Will a link to this be exposed somewhere in SC?

**Comment by HSSalman** [comment]
@otisg Yes, in the `Browse Examples` flyout where we also link to the Puppeteer docs.
frontend link

**Comment by otisg** [comment]
I was thinking that we may also want to expose it somewhere where we show failed runs for BMs with UJS?  That's what triggers people to look into their UJS (and/or get in touch with us), not when they are creating UJS.

**Review by fulyauluturk — APPROVED** [review]

**Review by hasan-wajahat — APPROVED** [review]
Good stuff 👍

**Comment by HSSalman** [comment]
> I was thinking that we may also want to expose it somewhere where we show failed runs for BMs with UJS? That's what triggers people to look into their UJS (and/or get in touch with us), not when they are creating UJS.

@otisg Good idea, I've added some links over there as well and added you as a reviewer to the SC PR with screenshots showcasing them.

**Pull request merged**
