### PR TITLE
Updated content with new CB images

### PR DESCRIPTION
**Pull request by fulyauluturk**
Screenshots updated for new CB
Component switch section added

### CODE REVIEW

**Review by cpipilas — APPROVED** [review]
LGTM

**Comment by mbonaci** [comment]
@fulyauluturk I've just noticed the new images while looking at the docs because of something Radu asked me and I noticed that the new images are missing the query, which the text refers to.

**Comment by mbonaci** [comment]
For example, the text says:
```
As you can see in the screenshot below and hopefully in your own chart, our query: Usage is still here, duplicated correctly from the first series
```
yet the query in the new image is empty.

**Comment by fulyauluturk** [comment]
Thank you Marko. I updated the images heatbar-5-enter-query_2, heatbar-7-severity-error_2
here 
https://github.com/sematext/docs/tree/master/docs/images/dashboards

**Pull request merged**
