### PR TITLE
SC-8894 added docs for Vercel - Synthetics integration

### PR DESCRIPTION
**Pull request by ssuvalija**

### CODE REVIEW

**Review by otisg — APPROVED** [review]

**Comment by HSSalman** [comment]
I've done the following:
- Updated and fixed up the Vercel-Synthetics docs which Selma worked on
- Mentioned Vercel-Synthetics on the existing Vercel-Logs page for cross-awareness
- Spotted some broken image links on the Vercel-Logs page, which ended up turning into a complete rework of it, since that page was referencing an older integration that had completely different installation steps and UI
  - Also modified the installation instructions in SC which, while not outdated, were still a bit messy with grammar/ordering
- Split up the **CI/CD Integrations** page into separate ones for each integration, as per the subtask in the ticket

**Review by fulyauluturk — APPROVED** [review]

**Comment by otisg** [comment]
> docs/images/integrations/vercel-logs-instructions.png

Are bullet points 1, 2, and 4 under "You get" more or less the same?  Should we merge them?

**Review by otisg — APPROVED** [review]
LGTM

**Comment by HSSalman** [comment]
> > docs/images/integrations/vercel-logs-instructions.png
> 
> Are bullet points 1, 2, and 4 under "You get" more or less the same? Should we merge them?

Something like `Insight into your whole Vercel account - View and store all data about your Vercel projects in one place`?

**Comment by otisg** [comment]
Maybe `Insight into all your Vercel projects' and apps' logs in one place`

**Comment by HSSalman** [comment]
Gotcha, updated in the Vercel-Synthetics epic

**Pull request merged**
