### PR TITLE
Initial stub

### PR DESCRIPTION
**Pull request by otisg**
Need to fill in the blanks, add anything that's missing, etc.

### CODE REVIEW

**Comment by adnanrahic** [comment]
@megastef can we also add mentions of:

- custom metrics - https://github.com/megastef/logagent-nodejs-monitor/commit/6366c83bc6534262123dc88a5a02b8908103f900#diff-168726dbe96b3ce427e7fedce31bb0bcR83-R105

- configuring monitoring for logagent - https://www.npmjs.com/package/@sematext/logagent-nodejs-monitor

- seeing charts for monitoring metrics in Sematext Cloud 
Screen Shot 2020-02-13 at 00 56 56

**Comment by megastef** [comment]
Sorry for the merge :) Changes are here https://github.com/sematext/docs/pull/175/files#diff-0ce64d8c6a2e1a282b01dd983821823c

**Comment by otisg** [comment]
Can I just merge this PR now, or....?

**Comment by adnanrahic** [comment]
LGTM :slightly_smiling_face:

**Pull request merged**
